include:
  - https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/container_scan-v2.yml

stages:
  - build
  - scan

build:alpine:
  stage: build
  image: registry.gitlab.com/jitesoft/dockerfiles/docker:latest
  variables:
    TAGS: "latest eap 14"
  script:
    - docker build --cache-from ${CI_REGISTRY_IMAGE}:latest -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} .
    - |
      for tag in $TAGS; do
        docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} ${CI_REGISTRY_IMAGE}:${tag}
        docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} quay.io/jitesoft/openjdk:${tag}
        docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} jitesoft/openjdk:${tag}
        docker push jitesoft/openjdk:${tag}
        docker push quay.io/jitesoft/openjdk:${tag}
        docker push ${CI_REGISTRY_IMAGE}:${tag}
      done
  tags:
    - jitesoft

scan:
  extends: .container_scanning
  variables:
    SCANNING_IMAGE_NAME: "${CI_REGISTRY_IMAGE}:latest"
    GIT_STRATEGY: none
